name: CI

on:
  pull_request:
    branches:
      - develop

env:
  JAVA_VERSION: '17'

jobs:

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Maven Package
        run: mvn clean package

      - name: Spotless Check
        run: mvn spotless:check

      - name: Maven Test
        run: mvn test
